### ISSUE TITLE
Use wrong map

### ISSUE THREAD

**Issue by tsec** [priyom/dyatlov#3]
I find the map of China is wrong http://rx.linkfanel.net/.Pls change it .

**Comment by linkfanel** [comment]
How so, wrong? What seems to be the problem with the map of China?

**Comment by tsec** [comment]
> How so, wrong? What seems to be the problem with the map of China?

![image](https://user-images.githubusercontent.com/5927829/126744296-98b116b8-fb86-4dec-a469-bd50410ebc77.png)
The openstreetmap is wrong about South Tibet. The right one is the image below
![image](https://user-images.githubusercontent.com/5927829/126744526-daf5c8cd-eeb0-48a5-92f8-5bb34f229ffe.png)

**Comment by linkfanel** [comment]
Thanks for your reply.

First, you give no source for the "right" map you uploaded, nor do you mention any reference or authority for the territorial claims that this map is supposed to illustrate. From what I know and understand, the OpenStreetMap map you uploaded shows a correct border marking South Tibet as Indian. If you won't make your case properly, that won't change. Please understand that I can't start changing things just because someone I don't know showed me a map taken from I don't know where: that wouldn't be very responsible of me.

Second, you mention it yourself so you understand that the map on http://rx.linkfanel.net/ is from OpenStreetMap, and that I have no direct control over it: you understand that I can't change it at my discretion. However OpenStreetMap is a community project open to contributions, so your suggestions would probably be more welcome there: I would suggest that you take the matter there instead of here, and our map will automatically follow whatever resolution is found upstream by OpenStreetMap. I am no fool though, I imagine what might be going on about this at OpenStreetMap, described in news articles such as https://restofworld.org/2021/the-mysterious-user-editing-a-global-open-source-map-in-chinas-favor/ or https://www.opindia.com/2021/04/chinese-users-edit-open-source-maps-of-borders-as-per-govt-instructions/

But I haven't seen any map tile provider that marks South Tibet as unambiguously Chinese either, like in the map you uploaded; are you aware of any? And alternatively, if you think OpenStreetMap is unacceptable, is there any other tile hosting provider you would suggest that we use or recommend? Remember that we have no budget for a paying service, and that we receive too much traffic to rely on the free quota of paying services like Google Maps.

Third, I have seen Chinese people like you before, sending complaints to random websites about Chinese territorial claims, although it was about Taiwan instead. The McMahon Line has served as the de facto border of India for over a century. What have Tibet or China accomplished during that time to assert control of territories claimed beyond it? In particular, in the 70 years since the PRC regained control of Tibet, what has it managed to accomplish about South Tibet? China has recognized the Line of Actual Control, isn't that recognition that it's failed to assert control beyond it? It's not so easy to enforce your claims on the ground. It's much easier, like the PRC has done with Taiwan as well, to hide your failure by diplomatically pressuring third-party countries and the international community to make them stop contradicting your still-empty claims. And what's even easier than that, is for Chinese individuals like you to bully random western websites with complaints to make them abide by the official Chinese view of the world.

The rest of the world and the internet will naturally take Chinese territorial claims more seriously and perhaps even recognize them when China manages to make them real on the ground or at least in international agreements. I think your claims should fundamentally start there; and I find what you're trying to do here on this bug tracker highly irrelevant and misplaced. If you want our map to show South Tibet as Chinese, I would suggest instead that you get involved in politics to steer and help China towards gaining actual control of it.

**Comment by linkfanel** [comment]
I'm going to close this. As I said, I don't see any actionable solution. Please note that we do support and suggest configuration with alternative map providers (for example Google Maps) that leave South Tibet as a disputed area, showing both borders as disputed; those who want to setup and configure their own map instance are free to choose those providers. As for us with rx.linkfanel.net however, as I said, we can't afford those paying alternatives.

You haven't explained your source or rationale about South Tibet so it's possible that you simply believe or assume that it is unquestioned Chinese territory. But from what I know and understand though, this is a disputed political and territorial claim from China. As such, even if there were solutions available, I wouldn't be likely to make changes just because of this. This is a software project about shortwave radio, not an outlet for playing into Chinese political claims.
